config/routes.rb
Rails.application.routes.draw do
  resources :students
  get '/courses/:course_id/semesters/:semester_number/top' => 'students#top', :as => 'top_students'
  get 'duplicated_ips' => 'students#duplicated_ip'
  get 'search' => 'students#search'
  root :to => 'students#index'
end

app/models/average_mark.rb
class AverageMark < ActiveRecord::Base
  belongs_to :semester
  belongs_to :student
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :groups,    :dependent => :destroy
  has_many :semesters, :through   => :groups
  has_many :students,  :through   => :groups

  scope :ordered, -> { order('number asc') }

  def available_semester_numbers
    semesters.select('number').uniq.order('number').map(&:number)
  end

  def human_number
    "#{number} курс"
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :course
  has_many   :students,  :dependent => :destroy
  has_many   :semesters, :dependent => :destroy
  has_many   :subjects,  :through   => :semesters
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :semester
  belongs_to :subject
  belongs_to :student

  scope :by_semester, ->(id) do
    joins(:semester).where(:semesters => { :id => id })
  end
  scope :by_subject, ->(id) do
    joins(:subject).where(:subjects => { :id => id })
  end
  scope :by_semester_and_subject, ->(semester_id, subject_id) do
    by_semester(semester_id).by_subject(subject_id)
  end

  after_create  :increase_average_mark
  after_destroy :decrease_average_mark

  private

  [:increase, :decrease].each do |action|
    define_method "#{action}_average_mark" do
      AverageMarkCalculator.new(self, action).set_mark_value
    end
  end
end

app/models/semester.rb
class Semester < ActiveRecord::Base
  belongs_to :group
  has_many   :semester_subjects, :dependent => :destroy
  has_many   :subjects,          :through   => :semester_subjects

  scope :ordered, -> { order('number') }

  def human_number
    "#{number} семестр"
  end

  def self.uniq_numbers
    self.ordered.select('number').uniq.map(&:number)
  end
end

app/models/semester_subject.rb
class SemesterSubject < ActiveRecord::Base
  belongs_to :semester
  belongs_to :subject
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
  has_one    :course,        :through   => :group
  has_many   :semesters,     :through   => :group
  has_many   :subjects,      :through   => :group
  has_many   :marks,         :dependent => :destroy
  has_many   :average_marks, :dependent => :destroy

  scope :ordered, -> { order(:surname, :name) }

  # топ 10 студентов курса в семестре
  scope :top, ->(number) do
    includes(:course, :group, :average_marks => [:semester]).
      where(:semesters => { :number => number }).
      order('average_marks.value desc, students.surname, students.name').limit(10)
  end

  # студенты с одинаковым ip адресом и как минимум одной характеристикой преподавателя
  scope :duplicate_ip_with_characteristic, -> do
    where("ip in (
          SELECT ip FROM students
          GROUP BY ip
          HAVING count(ip) > 1 AND count(characteristic) > 0)").
      order('ip')
  end

  # однокурсники с средним баллом между min и max в семестре и с именем name
  scope :for_search, ->(course_id, semester_number, min, max, name) do
    includes(:course, :average_marks => [:semester]).
      where(:courses => { :id => course_id }, :semesters => { :number => semester_number }).
      where("average_marks.value BETWEEN #{min} AND #{max}").
      where("LOWER(students.name) LIKE LOWER('#{name}%')")
  end

  normalize_attribute :email

  validates_presence_of :name, :surname, :email, :group_id
  validates_uniqueness_of :email

  def fullname
    [surname, name].join(' ')
  end

  # оценка по предмету в семестре
  def mark_for(semester_id, subject_id)
    marks.by_semester_and_subject(semester_id, subject_id).first
  end

  # средний балл в семестре
  def average_mark_for(semester_id)
    average_marks.find_by(:semester_id => semester_id)
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :semester_subjects, :dependent => :destroy
  has_many :semesters,         :through   => :semester_subjects
  has_many :marks,             :dependent => :destroy

  scope :by_semester, ->(semester_id) { joins(:semester_subjects).where(:semester_subjects => { :semester_id => semester_id }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :load_students, :only => [:index, :create, :destroy, :update]

  def index
    @courses = Course.ordered
    respond_to do |format|
      format.html
    end
  end

  def new
    @student = Student.new

    respond_to do |format|
      format.js
    end
  end

  def create
    respond_to do |format|
      format.js do
        @student = Student.new(student_params)
        if @student.save
          render :create
        else
          render :new
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.js do
        @student = Student.find(params[:id])
      end
    end
  end

  def edit
    respond_to do |format|
      format.js do
        @student = Student.find(params[:id])
      end
    end
  end

  def update
    respond_to do |format|
      format.js do
        @student = Student.find(params[:id])
        if @student.update_attributes(student_params)
          render :update
        else
          render :edit
        end
      end
    end
  end

  def destroy
    respond_to do |format|
      format.js do
        @student = Student.find(params[:id])
        @student.destroy
      end
    end
  end

  def top
    respond_to do |format|
      format.js do
        @course = Course.find(params[:course_id])
        @students = @course.students.top(params[:semester_number])
      end
    end
  end

  def duplicated_ip
    respond_to do |format|
      format.js do
        @students = Student.duplicate_ip_with_characteristic
      end
    end
  end

  def search
    search_params = params.fetch(:search, {})
    respond_to do |format|
      format.js do
        @students = Student.for_search(search_params[:course_id], search_params[:semester], search_params[:min].to_f, search_params[:max].to_f, search_params[:name])
      end
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :surname, :email, :ip, :registration_time, :birthdate, :group_id)
  end

  def load_students
    @students = Student.ordered
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentRegistry</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_duplicated_ip_list.html.erb
<table>
  <thead>
    <tr>
      <td>Фамилия</td>
      <td>Имя</td>
      <td>IP</td>
      <td>Характеристика</td>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.surname %></td>
        <td><%= student.name %></td>
        <td><%= student.ip %></td>
        <td><%= student.characteristic %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_form.html.erb
<%= simple_form_for @student, :remote => true do |f| %>
  <%= f.input :surname %>
  <%= f.input :name %>
  <%= f.association :group, :label_method => :number %>
  <%= f.input :birthdate %>
  <%= f.input :email %>
  <%= f.input :ip %>
  <%= f.input :registration_time %>
  <%= f.submit 'Сохранить' %>
<% end %>

app/views/students/_show_student.html.erb
<h2><%= @student.fullname %></h2>
<div class="characteristic">
  <h3>Характеристика преподавателя</h3>
  <%= @student.characteristic %>
</div>
<% @student.semesters.each do |semester| %>
  <h3><%= semester.human_number %></h3>
  <table>
    <thead>
      <tr>
        <td>Предмет</td>
        <td>Оценка</td>
      </tr>
    </thead>
    <tbody>
      <% semester.subjects.each do |subject| %>
        <tr>
          <td><%= subject.title %></td>
          <td><%= @student.mark_for(semester.id, subject.id).try(:value) %></td>
        </tr>
      <% end %>
      <tr>
        <td>Средний балл</td>
        <td><%= @student.average_mark_for(semester.id).try(:value) %></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/students/_student.html.erb
<tr>
  <td><%= link_to student.surname, student_path(student), :remote => true %></td>
  <td><%= student.name %></td>
  <td><%= student.group.number %></td>
  <td><%= I18n.l(student.birthdate) %></td>
  <td><%= student.email %></td>
  <td><%= student.ip %></td>
  <td><%= I18n.l(student.registration_time, format: :long) %></td>
  <td>
    <%= link_to "редактировать", edit_student_path(student), :remote => true %>
    <%= link_to "удалить", student_path(student), :method => :delete, :remote => true %>
  </td>
</tr>

app/views/students/_top_list.html.erb
<table>
  <thead>
    <tr>
      <td>Фамилия</td>
      <td>Имя</td>
      <td>Номер группы</td>
      <td>Средний балл</td>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.surname %></td>
        <td><%= student.name %></td>
        <td><%= student.group.number %></td>
        <td><%= student.average_marks.first.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/destroy.js.erb
$('.students_list').html("<%= escape_javascript(render @students) %>");

app/views/students/duplicated_ip.js.erb
$('.popup_container .container').html("<%= escape_javascript(render 'duplicated_ip_list') %>");
$('.popup_container').slideDown(350);

app/views/students/edit.js.erb
$('.popup_container .container').html("<%= escape_javascript(render 'form') %>");
$('.popup_container').slideDown(350);

app/views/students/index.html.erb
<div class="students">
  <table>
    <thead>
      <tr>
        <td>Фамилия</td>
        <td>Имя</td>
        <td>Номер группы</td>
        <td>Дата рождения</td>
        <td>Email</td>
        <td>IP адрес</td>
        <td>Время регистрации</td>
        <td>Действия</td>
      </tr>
    </thead>
    <tbody class='students_list'>
      <%= render @students %>
    </tbody>
  </table>
  <%= link_to "Добавить студента", new_student_path, :remote => true %>
  <div class="student-form" style='display:none'></div>
</div>

<div class="top">
  <h2>10 студентов с наивысшим баллом</h2>
  <% @courses.each do |course| %>
    <div class="course <%= course.number %>">
      <h3><%= course.human_number %></h3>
      <% course.available_semester_numbers.each do |semester_number| %>
        <span><%= link_to "#{semester_number} семестр", top_students_path(course.id, semester_number), :remote => true %></span>
      <% end %>
    </div>
  <% end %>
</div>

<div class="duplicated_ip">
  <h4><%= link_to "Дублирование IP адреса", duplicated_ips_path, :remote => true %></h4>
</div>

<div class="duplicated_ip">
  <h4><%= link_to "Поиск студентов", search_path, :remote => true %></h4>
</div>

<div class="popup_container">
  <%= link_to "x", '#', :class => 'close_link' %>
  <div class="container for_empty"></div>
</div>

app/views/students/new.js.erb
$('.student-form').html("<%= escape_javascript(render 'form') %>");
$('.student-form').slideDown(350);

app/views/students/search.js.erb
$('.popup_container .container').html("<%= escape_javascript(render 'search_list') %>");
$('.popup_container').slideDown(350);

app/views/students/show.js.erb
$('.popup_container .container').html("<%= escape_javascript(render 'show_student') %>");
$('.popup_container').slideDown(350);

app/views/students/top.js.erb
$('.popup_container .container').html("<%= escape_javascript(render 'top_list') %>");
$('.popup_container').slideDown(350);

app/views/students/update.js.erb
$('.students_list').html("<%= escape_javascript(render @students) %>");
$('.popup_container').slideUp(350);